namespace UltraNuke.Plotto.Domain;

public class Masterplot
{
    public List<ClauseA> ClauseAs = new List<ClauseA> {
        new ClauseA { Code="1",Description="一个恋爱中的人" },
        new ClauseA { Code="2",Description="一个已婚的人" },
        new ClauseA { Code="3",Description="一个无法无天的人" },
        new ClauseA { Code="4",Description="一个犯错的人" },
        new ClauseA { Code="5",Description="一个仁慈的人" },
        new ClauseA { Code="6",Description="一个保护者" },
        new ClauseA { Code="7",Description="一个理想主义者" },
        new ClauseA { Code="8",Description="一个受到义务影响的人" },
        new ClauseA { Code="9",Description="一个受到不利条件影响的人" },
        new ClauseA { Code="10",Description="一个怀有怨恨的人" },
        new ClauseA { Code="11",Description="一个受到虚伪影响的人" },
        new ClauseA { Code="12",Description="一个精明的人" },
        new ClauseA { Code="13",Description="一个受到神秘力量影响的人" },
        new ClauseA { Code="14",Description="一个正常的人" },
        new ClauseA { Code="15",Description="任何一个人" }
    };

    public List<ClauseB> ClauseBs = new()
    {
        new ClauseB { Code="1",Description="在获得高成就的奖励的承诺下进行困难的事业", Conflicts = new string[] { "110" } },
        new ClauseB { Code="2",Description="在某些义务禁止爱情的时间里坠入爱河", Conflicts = new string[] { "" } },
        new ClauseB { Code="3",Description="通过勇气的考验证明爱的力量", Conflicts = new string[] { "" } },
        new ClauseB { Code="4",Description="因为过度的幻想而误判一段恋情", Conflicts = new string[] { "" } },
        new ClauseB { Code="5",Description="卷入一段没有希望的恋情，并寻求尽量好地处理令人气馁的情况", Conflicts = new string[] { "" } },
        new ClauseB { Code="6",Description="挑战在爱之旅中不变的真理：“东是东，西是西，二者永不会相遇”", Conflicts = new string[] { "" } },
        new ClauseB { Code="7",Description="卷入一段遇到意想不到障碍的恋情", Conflicts = new string[] { "" } },
        new ClauseB { Code="8",Description="面对一个财富只有按照恋爱事情的某种方式才能获得的情况", Conflicts = new string[] { "" } },
        new ClauseB { Code="9",Description="面对一个考验，如果提供更多物质财富就会失去爱情", Conflicts = new string[] { "" } },
        new ClauseB { Code="10",Description="由于误判而导致疏远", Conflicts = new string[] { "" } },
        new ClauseB { Code="11",Description="面对一个只有勇气和奉献才能挽救所爱之人的命运的情况", Conflicts = new string[] { "" } },
        new ClauseB { Code="12",Description="由于不忠在爱情中陷入不幸", Conflicts = new string[] { "" } },
        new ClauseB { Code="13",Description="试图通过狡猾躲避不幸", Conflicts = new string[] { "" } },
        new ClauseB { Code="14",Description="由于狡猾的阴谋者而陷入不幸", Conflicts = new string[] { "" } },
        new ClauseB { Code="15",Description="在不幸中找到支持力量", Conflicts = new string[] { "" } },
        new ClauseB { Code="16",Description="由于一个人在信任中坦白了一个犯罪的秘密而从不幸中解脱出来", Conflicts = new string[] { "" } },
        new ClauseB { Code="17",Description="忍受不幸并试图以光荣的方式实现所珍视的目标", Conflicts = new string[] { "" } },
        new ClauseB { Code="18",Description="反抗控制个人能力并将其置于服从之下的力量", Conflicts = new string[] { "" } },
        new ClauseB { Code="19",Description="遭遇不幸并被抛弃在原始、孤立和野蛮的环境中", Conflicts = new string[] { "" } },
        new ClauseB { Code="20",Description="卷入不幸的情况", Conflicts = new string[] { "" } },
        new ClauseB { Code="21",Description="由于误判而陷入不幸", Conflicts = new string[] { "" } },
        new ClauseB { Code="22",Description="由于误判而走错了路", Conflicts = new string[] { "" } },
        new ClauseB { Code="23",Description="卷入一个涉及误判和怀疑的复杂局面", Conflicts = new string[] { "" } },
        new ClauseB { Code="24",Description="在执行一项事业时成为误判的受害者", Conflicts = new string[] { "" } },
        new ClauseB { Code="25",Description="寻求拯救被指控犯罪的人", Conflicts = new string[] { "" } },
        new ClauseB { Code="26",Description="悄悄地寻求拯救另一个人的危险", Conflicts = new string[] { "" } },
        new ClauseB { Code="27",Description="拒绝背叛他人的秘密，并因为拒绝而面对迫害", Conflicts = new string[] { "" } },
        new ClauseB { Code="28",Description="面对一个情况，即深受尊敬的人的不幸需要勇气和智慧的企业", Conflicts = new string[] { "" } },
        new ClauseB { Code="29",Description="帮助另一个人隐藏世界上一个决定性的秘密", Conflicts = new string[] { "" } },
        new ClauseB { Code="30",Description="全心全意地为需要帮助的不幸者服务，并提供最重要的帮助", Conflicts = new string[] { "" } },
        new ClauseB { Code="31",Description="过着孤独而没有欢乐的生活，寻求伙伴关系", Conflicts = new string[] { "" } },
        new ClauseB { Code="32",Description="因为崇高的理想主义而寻求隐藏身份", Conflicts = new string[] { "" } },
        new ClauseB { Code="33",Description="秘密而有荣誉的动机反抗一项被认为不光彩的命令", Conflicts = new string[] { "" } },
        new ClauseB { Code="34",Description="希望改善某些邪恶条件的情况下，发动一场叛乱的事业", Conflicts = new string[] { "" } },
        new ClauseB { Code="35",Description="卷入一个挑战所珍视的理想价值的复杂局面", Conflicts = new string[] { "" } },
        new ClauseB { Code="36",Description="经历一次导致显著性格变化的经历", Conflicts = new string[] { "" } },
        new ClauseB { Code="37",Description="寻求克服困难，实现所珍视的理想", Conflicts = new string[] { "" } },
        new ClauseB { Code="38",Description="犯下一个严重的错误，悄悄地寻求消除它的恶劣影响", Conflicts = new string[] { "" } },
        new ClauseB { Code="39",Description="放弃所珍视的野心来执行一项义务", Conflicts = new string[] { "" } },
        new ClauseB { Code="40",Description="在一项义务受到另一项义务的反对的情况下开始一项事业", Conflicts = new string[] { "" } },
        new ClauseB { Code="41",Description="发现一项义务与野心、倾向或必要性不一致", Conflicts = new string[] { "" } },
        new ClauseB { Code="42",Description="在诚挚地执行一项义务的同时陷入不幸", Conflicts = new string[] { "" } },
        new ClauseB { Code="43",Description="寻求在执行一项事业时克服个人局限", Conflicts = new string[] { "" } },
        new ClauseB { Code="44",Description="寻求通过不同的方法克服个人局限", Conflicts = new string[] { "" } },
        new ClauseB { Code="45",Description="寻求推进一项事业，并遇到家庭情绪作为障碍", Conflicts = new string[] { "" } },
        new ClauseB { Code="46",Description="寻求报复一个严重的错误，无论是真实还是幻想的", Conflicts = new string[] { "" } },
        new ClauseB { Code="47",Description="找到（表面上）一个极为渴望的物体，并（表面上）获得这个物体", Conflicts = new string[] { "" } },
        new ClauseB { Code="48",Description="在一个完全诚实的企业中扮演犯罪分子的角色", Conflicts = new string[] { "" } },
        new ClauseB { Code="49",Description="在开始某项事业时扮演一个虚构的角色", Conflicts = new string[] { "" } },
        new ClauseB { Code="50",Description="因为一个不同寻常的动机而从事狡猾的事业", Conflicts = new string[] { "" } },
        new ClauseB { Code="51",Description="设计一个聪明和似是而非的错觉，以推进某些事业", Conflicts = new string[] { "" } },
        new ClauseB { Code="52",Description="遇到一个潜在的违法者并试图阻止违法行为", Conflicts = new string[] { "" } },
        new ClauseB { Code="53",Description="反对一个狡猾的阴谋家的计划，", Conflicts = new string[] { "" } },
        new ClauseB { Code="54",Description="卷入一个拥有神秘力量的物品所带来的迷惑性复杂局面，", Conflicts = new string[] { "" } },
        new ClauseB { Code="55",Description="卷入一个神秘的复杂局面，并寻求尽可能多地利用奇怪的经历，", Conflicts = new string[] { "" } },
        new ClauseB { Code="56",Description="寻求测试一个神秘信息的价值，并卷入奇怪的复杂局面，", Conflicts = new string[] { "" } },
        new ClauseB { Code="57",Description="寻求解开一个谜团的复杂局面，", Conflicts = new string[] { "" } },
        new ClauseB { Code="58",Description="参与一个企业，然后神秘地消失，", Conflicts = new string[] { "" } },
        new ClauseB { Code="59",Description="参与一个神秘的企业，并接触到神秘学和奇幻的东西。", Conflicts = new string[] { "" } },
        new ClauseB { Code="60",Description="因为好奇心被神秘所引发，卷入一个奇怪的企业。", Conflicts = new string[] { "" } },
        new ClauseB { Code="61",Description="意识到一个重要的秘密，要求采取果断行动，", Conflicts = new string[] { "" } },
        new ClauseB { Code="62",Description="卷入任何类型的复杂局面。", Conflicts = new string[] { "" } },
    };

    public List<ClauseC> ClauseCs = new List<ClauseC> {
        new ClauseC { Code="1",Description="在不幸的事业中付出严重的代价，" },
        new ClauseC { Code="2",Description="从严峻的纠缠中幸福地脱颖而出。" },
        new ClauseC { Code="3",Description="挫败了一个有罪的阴谋家，并击败了一个狡猾的阴计。" },
        new ClauseC { Code="4",Description="承担了一个直接导致灾难的角色。" },
        new ClauseC { Code="5",Description="在艰难的考验中凭借极大的智慧脱颖而出。" },
        new ClauseC { Code="6",Description="在执行一项任务时作出了至高无上的牺牲。" },
        new ClauseC { Code="7",Description="当他们的谬误被揭示出来时，改变了某些意见。" },
        new ClauseC { Code="8",Description="取得精神胜利" },
        new ClauseC { Code="9",Description="在艰苦的任务中取得成功和幸福。" },
        new ClauseC { Code="10",Description="经历了一次经历，纠正了一个错误。" },
        new ClauseC { Code="11",Description="发现了试图与现实不同的愚蠢行为。" },
        new ClauseC { Code="12",Description="从严峻的纠缠中拯救了正直。" },
        new ClauseC { Code="13",Description="最终来到了无解的悬念之墙。" },
        new ClauseC { Code="14",Description="取得了完整而永久的性格转变" },
        new ClauseC { Code="15",Description="遭遇了任何好或坏的命运。" },
    };

    public List<Group> Groups = new List<Group> {
        new Group { Code="1",Description="爱情和求爱冲突。" },
        new Group { Code="2",Description="婚姻生活冲突。" },
        new Group { Code="3",Description="企业冲突。" },
    };

    public List<SubGroup> SubGroups = new List<SubGroup> {
        new SubGroup { GroupCode="1",Code="1",Description="爱情的开始冲突" },
        new SubGroup { GroupCode="1",Code="2",Description="爱情的不幸冲突" },
        new SubGroup { GroupCode="1",Code="3",Description="婚约的冲突" },
        new SubGroup { GroupCode="1",Code="4",Description="爱情的拒绝冲突" },
        new SubGroup { GroupCode="1",Code="5",Description="婚姻的冲突" },
        new SubGroup { GroupCode="3",Code="1",Description="不幸的冲突" },
        new SubGroup { GroupCode="3",Code="2",Description="错误判断的冲突" },
        new SubGroup { GroupCode="3",Code="3",Description="帮助的冲突" },
        new SubGroup { GroupCode="3",Code="4",Description="解脱的冲突" },
        new SubGroup { GroupCode="3",Code="5",Description="理想主义的冲突" },
        new SubGroup { GroupCode="3",Code="6",Description="义务的冲突" },
        new SubGroup { GroupCode="3",Code="7",Description="必要性的冲突" },
        new SubGroup { GroupCode="3",Code="8",Description="机会的冲突" },
        new SubGroup { GroupCode="3",Code="9",Description="个人局限的冲突" },
        new SubGroup { GroupCode="3",Code="10",Description="模拟的冲突" },
        new SubGroup { GroupCode="3",Code="11",Description="狡猾的冲突" },
        new SubGroup { GroupCode="3",Code="12",Description="违法的冲突" },
        new SubGroup { GroupCode="3",Code="13",Description="报复的冲突" },
        new SubGroup { GroupCode="3",Code="14",Description="神秘的冲突" },
        new SubGroup { GroupCode="3",Code="15",Description="启示的冲突" },
    };

    public List<Character> Characters = new List<Character> {
        new Character { Code="A",Description="男主角", Sex = SexEnum.男性},
        new Character { Code="A-2",Description="A的男性朋友", Sex = SexEnum.男性},
        new Character { Code="A-3",Description="A的男性对手或敌人", Sex = SexEnum.男性},
        new Character { Code="A-4",Description="男性陌生人", Sex = SexEnum.男性},
        new Character { Code="A-5",Description="男性罪犯", Sex = SexEnum.男性},
        new Character { Code="A-6",Description="男性法律执法人员", Sex = SexEnum.男性},
        new Character { Code="A-7",Description="男性下属，雇员", Sex = SexEnum.男性},
        new Character { Code="A-8",Description="男性工具符号", Sex = SexEnum.男性},
        new Character { Code="A-9",Description="男性上司，雇主，权威人士", Sex = SexEnum.男性},
        new Character { Code="B",Description="女主角", Sex = SexEnum.女性},
        new Character { Code="B-2",Description="B的女性朋友", Sex = SexEnum.女性},
        new Character { Code="B-3",Description="B的女性对手或敌人", Sex = SexEnum.女性},
        new Character { Code="B-4",Description="女性陌生人", Sex = SexEnum.女性},
        new Character { Code="B-5",Description="女性罪犯", Sex = SexEnum.女性},
        new Character { Code="B-6",Description="女性法律执法人员", Sex = SexEnum.女性},
        new Character { Code="B-7",Description="女性下属，雇员", Sex = SexEnum.女性},
        new Character { Code="B-8",Description="女性工具符号", Sex = SexEnum.女性},
        new Character { Code="B-9",Description="女性上司，雇主，权威人士", Sex = SexEnum.女性},
        new Character { Code="F-A",Description="A的父亲", Sex = SexEnum.男性},
        new Character { Code="M-A",Description="A的母亲", Sex = SexEnum.女性},
        new Character { Code="BR-A",Description="A的兄弟", Sex = SexEnum.男性},
        new Character { Code="SR-A",Description="A的姐妹", Sex = SexEnum.女性},
        new Character { Code="SN-A",Description="A的儿子", Sex = SexEnum.男性},
        new Character { Code="D-A",Description="A的女儿", Sex = SexEnum.女性},
        new Character { Code="U-A",Description="A的叔叔", Sex = SexEnum.男性},
        new Character { Code="AU-A",Description="A的阿姨", Sex = SexEnum.女性},
        new Character { Code="CN-A",Description="A的堂亲", Sex = SexEnum.任何},
        new Character { Code="NW-A",Description="A的侄子", Sex = SexEnum.男性},
        new Character { Code="NC-A",Description="A的侄女", Sex = SexEnum.女性},
        new Character { Code="GF-A",Description="A的祖父", Sex = SexEnum.男性},
        new Character { Code="GM-A",Description="A的祖母", Sex = SexEnum.女性},
        new Character { Code="SF-A",Description="A的继父", Sex = SexEnum.男性},
        new Character { Code="SM-A",Description="A的继母", Sex = SexEnum.女性},
        new Character { Code="GCH-A",Description="A的孙辈", Sex = SexEnum.任何},
        new Character { Code="F-B",Description="B的父亲", Sex = SexEnum.男性},
        new Character { Code="M-B",Description="B的母亲", Sex = SexEnum.女性},
        new Character { Code="BR-B",Description="B的兄弟", Sex = SexEnum.男性},
        new Character { Code="SR-B",Description="B的姐妹", Sex = SexEnum.女性},
        new Character { Code="SN-B",Description="B的儿子", Sex = SexEnum.男性},
        new Character { Code="D-B",Description="B的女儿", Sex = SexEnum.女性},
        new Character { Code="U-B",Description="B的叔叔", Sex = SexEnum.男性},
        new Character { Code="BU-B",Description="B的阿姨", Sex = SexEnum.女性},
        new Character { Code="CN-B",Description="B的堂亲", Sex = SexEnum.任何},
        new Character { Code="NW-B",Description="B的侄子", Sex = SexEnum.男性},
        new Character { Code="NC-B",Description="B的侄女", Sex = SexEnum.女性},
        new Character { Code="GF-B",Description="B的祖父", Sex = SexEnum.男性},
        new Character { Code="GM-B",Description="B的祖母", Sex = SexEnum.女性},
        new Character { Code="SF-B",Description="B的继父", Sex = SexEnum.男性},
        new Character { Code="SM-B",Description="B的继母", Sex = SexEnum.女性},
        new Character { Code="GCH-B",Description="B的孙辈", Sex = SexEnum.任何},
        new Character { Code="CH",Description="一个孩子", Sex = SexEnum.任何},
        new Character { Code="AX",Description="一个神秘的男人，或一个不寻常的人物", Sex = SexEnum.男性},
        new Character { Code="BX",Description="一个神秘的女人，或一个不寻常的人物", Sex = SexEnum.女性},
        new Character { Code="X",Description="一个无生命的物体，一个谜一样的物体，一个不确定的数量。", Sex = SexEnum.无},
        new Character { Code="",Description="", Sex = SexEnum.女性},
    };
}




